### PR TITLE
Fix fetching team data on schedule API for the NBA

### PR DESCRIPTION
**Pull request by mathieujobin**
CC: @djhalaninext @BlaneCordes @dyang12

### CODE REVIEW

**Comment by RLovelett** [comment]
I'm not near a computer right now. But why did the build fail?

**Comment by mathieujobin** [comment]
Ruby 1.9.3 and 2.1 had different issues with bundler and other packages.
Seems unrelated with my changes.

Le mar. 15 déc. 2015 à 18:22, Ryan Lovelett <notifications@github.com> a
écrit :

**Comment by RLovelett** [comment]
Alright I'll take a look at it later tonight. Hopefully I'll merge it sometime tomorrow.

**Comment by mathieujobin** [comment]
looks like I got 3 working solutions....

failures for ruby 2.1 and 2.2 were temporary failures.. restarting the build worked.

for 1.9.3 we have three options
- [take out coveralls](https://travis-ci.org/venuenext/sports_data_api/builds/97243289) for 1.9.3
- [explicitly lock tins to 0.x](https://travis-ci.org/venuenext/sports_data_api/builds/97240976) which is a dependency to coveralls
- [upgrade bundler](https://travis-ci.org/mathieujobin/sports_data_api/builds/97236674) to 1.11 from 1.7 on the travis server 

last one, I'm only touching the .travis.yml file, so it might be best

**Comment by RLovelett** [comment]
Thank you for looking into this. [Since Ruby 1.9.3 support was dropped in February of this year](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) I think it is time for me to sunset support for it as well. I'm fine with just removing the configuration from the Travis build.

**Comment by RLovelett** [comment]
Please change the version from `0.2.4` to `0.3.0`. Since we are dropping support for a Ruby interpreter lets go up a minor revision.

**Comment by mathieujobin** [comment]
you can relaunch the build, it passed on my fork https://travis-ci.org/venuenext/sports_data_api

**Comment by RLovelett** [comment]
I made a branch where all I did was remove support for 1.9.3 and the builds are consistently failing. [See](https://travis-ci.org/RLovelett/sports_data_api/builds/97257705).

I'm totally confused. Especially cause it builds on your fork and not on this repo.

**Comment by RLovelett** [comment]
... and now they pass on Travis. I give up.

**Comment by mathieujobin** [comment]
I rebased after your other merge

**Comment by RLovelett** [comment]
After all this I've realized #51 allowed me to restore Ruby 1.9.3. So I did that with #55. Therefore, I've switched the version back from `0.3.0` to `0.2.4` and pushed a new tag and revision to RubyGems.

Thank you for your contribution.

**Pull request merged**
