### PR TITLE
Fix test reporter

### PR DESCRIPTION
**Pull request by trevorrjohn**
code climate test reporter is deprecated.

This also removes the rvm specific files. I don't think these should be checked in.

### CODE REVIEW

**Comment by trevorrjohn** [comment]
So this is just failing on ruby version 2.5-dev. Not sure if we can fix this nor if we should fix this. My thought is to change the travis file to only look at released ruby versions.

**Comment by trevorrjohn** [comment]
Hey so I went through and updated the appropriate gems. Also removed test support for 1.9.3 and 2.0.0, while they are passing they are no longer supported by the ruby team and I felt like they don't need to be supported here either. Let me know what you think. My plan now is to start implementing golf and would love to hear your thoughts about it.

**Comment by RLovelett** [comment]
@trevorrjohn I'm writing a lot less Ruby code these days (in that it is near zero). I'm not really able to keep up with this in the way I hoped in the past.

Are you interested in being added as a contributor?

**Comment by trevorrjohn** [comment]
Yes! Definitely interested, @nicolo and I are working on implementing golf
at the moment so we would both love to be contributors.

**Comment by RLovelett** [comment]
I added him as well.

**Pull request merged**
