### PR TITLE
upgrade bundler

### PR DESCRIPTION
**Pull request by mathieujobin**
newest bundler is able to figure which tins is compatible with 1.9.3

### CODE REVIEW

**Comment by RLovelett** [comment]
Since I am going to drop support for 1.9.3 is this still necessary?

**Comment by mathieujobin** [comment]
guess not.

**Comment by RLovelett** [comment]
Okey dokey.

**Comment by RLovelett** [comment]
This actually seems to make everything work! I'm putting this one in.

**Comment by RLovelett** [comment]
Ok so this is likely a placebo. I have no idea. The tests pass locally and I'm tired of messing with travis so I'm going to merge #50 too.

**Pull request merged**
