### PR TITLE
NCAAMB Implementation

### PR DESCRIPTION
**Pull request by nicolo**
Here is the implementation of NCAAMB. I modeled it after the NBA implementation. There is addition the ability to pull the tournament list and tournament schedule.

### CODE REVIEW

**Comment by RLovelett** [comment]
Please rebase off of master. [Example here](https://github.com/RLovelett/sports_data_api/pull/41#issuecomment-76325573)

Once the tests are passing I'll look over it. Thanks for your effort @nicolo.

**Comment by nicolo** [comment]
This has been rebased and should be all set to review

**Comment by RLovelett** [comment]
@nicolo I have reviewed and merged this. To stop another rebase and push I just went ahead and did it for you. The new commit is db57c1370dcdcfd54bed3f56e9f6a894626753d3 (and you still get credit for the commit).

It just doesn't automatically mark this PR as closed. Therefore I am manually closing it.

Thanks for the contribution!

**Comment by RLovelett** [comment]
Also just to let you know I just published v0.2.1 and that contains all of your PR code.

**Pull request closed without merging**
